[package]
name = "check_vectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsecp256k1 = "0.7.0"
hex = "0.4.3"
serde_json = "1.0"
